### ISSUE TITLE
What Netlify subscription does it require?

### ISSUE THREAD

**Issue by swiing** [Qimath/sandbox-client#1]
Thanks for this sandbox repo.

Question for clarification: does it require any specific type of Netlify subscription level? (including for external provider authentication). Would very much appreciate feedback on this.

Cheers

**Comment by Qimath** [comment]
This runs on the Basic (free) Netlify plan, without any subscription required

Authentication could also be adapted if the sandbox is hosted on a different provider of course.
Alternatively, it is hosted directly on https://sandbox.chrisp.chat for direct free usage :)

**Comment by swiing** [comment]
Thanks for the prompt response and clarification.
Closing this issue
